#######
# Infrastructure
#######
#postgres:
#  image: postgres:9.5
#  ports:
#    - "5432:5432"
#  environment:
#    - POSTGRES_USER=play
#    - POSTGRES_PASSWORD=secret
#  volumes:
#    - /var/lib/postgresql/data

elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
